spring:
 application:
  name: 
   smkt-users
 datasource:
  url:
   jdbc:mysql://172.0.0.20:3306/SMKT_USERS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
  username:
   smkt
  password:
   Smkt@123
  driver-class-name: 
     com.mysql.cj.jdbc.Driver     
 jpa:
    database-platform:
     org.hibernate.dialect.MySQL8Dialect  
    hibernate:
     ddl-auto:
      create
       
server:
 port: 
  4060

eureka:
 instance:
  instance-id: 
   ${spring.application.name}:${spring.application.instance_id:${random.value}}
 client:
  service-url:
   defaultZone: 
    http://172.0.0.3:8761/eureka
  fetchRegistry: true

logging:
 level:
  org:
   hibernate:
    SQL:
     debug
