spring:
 application:
  name: 
   smkt-users
 datasource:
  url:
   jdbc:mysql://localhost:3306/SMKT_USERS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
  username:
   root
  password:
   root
  driver-class-name: 
     com.mysql.cj.jdbc.Driver     
 jpa:
    database-platform:
     org.hibernate.dialect.MySQL8Dialect  
    hibernate:
     ddl-auto:
      create-drop

server:
 port: 
  4060

eureka:
 instance:
  instance-id: 
   ${spring.application.name}:${spring.application.instance_id:${server.port}}
 client:
  service-url:
   defaultZone: 
    http://localhost:8761/eureka
  fetchRegistry: true

logging:
 level:
  org:
   hibernate:
    SQL:
     debug
     
     
default:
 params:
  roles:
   id: 2
   
oauth:
 user: smkt-users
 secret: smkt-users
 app-key-secret: 58c4581b7d7f9ab295ac3a273d15ad77af90d429f986dbfe82ca3241d9ef3dbb
 
 
 
superadmin:
 id: 1
 
scopes:
 super: users.super
 adm: users.adm
 read-min: users.read-min
 update-self: users.update-self
 
 
 
 
 
sonar:
 jdbc:
  dialect: mssql
 projectKey: smkt_users
 projectName: smkt_users
 projectVersion: 1.0
 sources: src
 language: java
 binaries: build/classes
 tests: junit
 dynamicAnalysis: reuseReports
 junit:
  reportsPath: build/test-reports
 java:
  coveragePlugin: jacoco